Repository kalgory/Web_Kalgory, pull requests merged in 2021-02, with the labels that each got.

#22 Feature/user route
  firestore.rules
  src/App.vue
  src/components/app/AppBar.vue
  src/components/app/bar/BarUser.vue
  src/components/app/bar/user/UserAvatar.vue
  src/components/auth/sign-in/SignInForm.vue
  src/components/auth/sign-up/SignUpForm.vue
  src/components/user/profile/ProfileContainer.vue
  src/plugins/firebase/firestore/user/index.js
  src/router/index.js
  src/router/routes.js
  src/store/modules/auth.js
Labels: enhancement

#23 Feature/modify posts
  package-lock.json
  src/components/community/default/DefaultCard.vue
  src/components/community/default/DefaultCardAction.vue
  src/components/community/default/DefaultCardText.vue
  src/components/community/default/DefaultCardTitle.vue
  src/components/community/question/post/create/CreateForm.vue
  src/components/community/question/post/read/ReadCard.vue
  src/components/community/question/posts/PostsDataIterator.vue
  src/components/community/question/posts/PostsTable.vue
  src/components/community/question/posts/data/DataCard.vue
  src/plugins/firebase/firestore/community/index.js
  src/plugins/firebase/firestore/community/reference.js
  src/views/community/CommunityDefault.vue
  src/views/community/question/QuestionPosts.vue
Labels: enhancement

#24 Feature/error handler
  package-lock.json
  package.json
  src/App.vue
  src/components/app/bar/BarUser.vue
  src/components/auth/AuthCard.vue
  src/components/auth/AuthCardTitle.vue
  src/components/auth/sign-in/SignInForm.vue
  src/components/auth/sign-up/SignUpForm.vue
  src/components/user/profile/ProfileContainer.vue
  src/main.js
  src/plugins/firebase/auth/index.js
  src/plugins/toasted/index.js
  src/router/index.js
  src/router/routes.js
Labels: bug, enhancement

#26 Feature/validate auth
  .github/pull_request_template.md
  src/App.vue
  src/assets/btn-google-light-normal.svg
  src/components/auth/AuthCard.vue
  src/components/auth/AuthCardTitle.vue
  src/components/auth/form/email/EmailTextField.vue
  src/components/auth/form/name/NameTextField.vue
  src/components/auth/form/password/PasswordTextField.vue
  src/components/auth/sign-in/SignInForm.vue
  src/components/auth/sign-up/SignUpForm.vue
  src/components/auth/social/SocialContainer.vue
  src/plugins/firebase/auth/index.js
  src/plugins/toasted/index.js
  src/views/auth/AuthSignIn.vue
  src/views/auth/AuthSignUp.vue
Labels: documentation, enhancement

#25 Feature/apply markdown
  package-lock.json
  package.json
  src/components/community/CommunityToolbar.vue
  src/components/community/question/post/create/CreateForm.vue
  src/components/community/question/posts/PostsDataIterator.vue
  src/components/community/question/posts/data/DataCard.vue
  src/main.js
  src/plugins/firebase/firestore/community/index.js
  src/views/BaseCommunity.vue
Labels: enhancement

#27 Feature/auth route
  package-lock.json
  src/App.vue
  src/components/auth/AuthCard.vue
  src/components/auth/form/email/EmailTextField.vue
  src/components/auth/form/name/NameTextField.vue
  src/components/auth/form/password/PasswordTextField.vue
  src/components/auth/sign-in/SignInForm.vue
  src/components/auth/sign-up/SignUpForm.vue
  src/router/routes.js
  src/views/BaseAuth.vue
  src/views/auth/AuthSignIn.vue
  src/views/auth/AuthSignUp.vue
Labels: bug, enhancement

#31 Feature/modify ux
  src/components/app/AppBar.vue
  src/components/community/CommunityNavigationDrawer.vue
  src/components/community/CommunityToolbar.vue
  src/components/community/default/DefaultCardAction.vue
  src/components/community/question/posts/PostsDataIterator.vue
  src/components/community/question/posts/data/DataCard.vue
  src/views/BaseCommunity.vue
  src/views/community/CommunityQuestion.vue
  src/views/community/question/QuestionPost.vue
  src/views/community/question/QuestionPosts.vue
Labels: enhancement

#30 Feature/email verify
  package-lock.json
  package.json
  src/App.vue
  src/components/app/AppBar.vue
  src/components/auth/AuthCard.vue
  src/components/auth/form/email/EmailTextField.vue
  src/components/auth/form/name/NameTextField.vue
  src/components/auth/form/password/PasswordTextField.vue
  src/components/auth/sign-in/SignInCard.vue
  src/components/auth/sign-in/SignInForm.vue
  src/components/auth/sign-up/SignUpCard.vue
  src/components/auth/sign-up/SignUpForm.vue
  src/components/auth/verify/VerifyCard.vue
  src/router/routes.js
  src/store/modules/auth.js
  src/views/auth/AuthSignIn.vue
  src/views/auth/AuthSignUp.vue
  src/views/auth/AuthVerify.vue
Labels: bug, enhancement

#34 Feature/email verify
  src/App.vue
  src/components/app/AppBar.vue
  src/components/auth/AuthCardTitle.vue
  src/components/auth/sign-in/SignInForm.vue
  src/components/auth/sign-up/SignUpForm.vue
  src/components/auth/social/SocialContainer.vue
  src/components/auth/verify/VerifyCard.vue
  src/router/routes.js
  src/store/index.js
  src/store/modules/auth/index.js
  src/views/BaseAuth.vue
  src/views/auth/AuthSignIn.vue
  src/views/auth/AuthSignUp.vue
  src/views/auth/AuthVerify.vue
Labels: bug, enhancement

#35 Feature/email verify
  src/App.vue
  src/components/app/AppBar.vue
  src/components/auth/AuthCardTitle.vue
  src/components/auth/sign-in/SignInForm.vue
  src/components/auth/sign-up/SignUpForm.vue
  src/components/auth/social/SocialContainer.vue
  src/components/auth/verify/VerifyCard.vue
  src/router/routes.js
  src/store/index.js
  src/store/modules/auth/index.js
  src/views/BaseAuth.vue
  src/views/auth/AuthSignIn.vue
  src/views/auth/AuthSignUp.vue
  src/views/auth/AuthVerify.vue
Labels: enhancement
